############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2

[[main]]
name = "FAQ"
url = "/faq"
weight = 3

# footer menu
[[footer]]
name = "Send Us a Message"
url = "/contact"
weight = 1
